[book]
authors = ["JavaliMZ"]
language = "pt"
multilingual = false
src = "src"
title = "WriteUps HackTheBox - by JavaliMZ"


[output.html]
additional-css = ["theme/css/additional.css",]
additional-js = []
default-theme = "Ayu"
preferred-dark-theme = "Ayu"
site-url = "/"

[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 0